name: build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Check out the source code for XCode
        uses: actions/checkout@v3
      - name: Build the XCode project
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: WebSaver.xcodeproj
          scheme: WebSaver
          destination: platform=macOS
          action: build
      - name: Upload the build directory as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: WebSaver
          path: /Users/runner/Library/Developer/Xcode/DerivedData//WebSaver-dnfwrjsdcytbqjcmuceoafwrnokj/Build/Products/Debug
      - name: Pack the build directory for release
        run: zip WebSaver.zip /Users/runner/Library/Developer/Xcode/DerivedData//WebSaver-dnfwrjsdcytbqjcmuceoafwrnokj/Build/Products/Debug/
      - name: Cut a new release
        uses: ncipollo/release-action@v1
        with:
          artifacts: WebSaver.zip
