name: build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out the source code for XCode
        uses: actions/checkout@v3
      - name: Build the XCode project
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: WebSaver.xcodeproj
          scheme: WebSaver
          destination: platform=macOS
          action: build
      - name: Upload the build directory as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: WebSaver
          path: /Users/runner/Library/Developer/Xcode/DerivedData//WebSaver-dnfwrjsdcytbqjcmuceoafwrnokj/Build/Products/Debug
